### ISSUE TITLE
Provisioners will not be run since container doesn't support SSH

### ISSUE THREAD

**Issue by sebastian-palma** [scalingexcellence/scrapybook#10]
How could I see what's inside the box?
Reading the book and doing what it says is very difficult to not get crazy, later than run `$ vagrant up --no-parallel` I try to run `$ vagrant ssh` and it doesn't anything, no errors, nothing. The only clue that I have is when running `$ vagrant up` it gives a message saying the next:
`$ vagrant up`
`Bringing machine 'web' up with 'docker' provider...`
`Bringing machine 'spark' up with 'docker' provider...`
`Bringing machine 'es' up with 'docker' provider...`
`Bringing machine 'redis' up with 'docker' provider...`
`Bringing machine 'mysql' up with 'docker' provider...`
`Bringing machine 'scrapyd1' up with 'docker' provider...`
`Bringing machine 'scrapyd2' up with 'docker' provider...`
`Bringing machine 'scrapyd3' up with 'docker' provider...`
`Bringing machine 'dev' up with 'docker' provider...`
`==> web: Provisioners will not be run since container doesn't support SSH.`
`==> mysql: Provisioners will not be run since container doesn't support SSH.`
`==> scrapyd2: Provisioners will not be run since container doesn't support SSH.`
`==> dev: Provisioners will not be run since container doesn't support SSH.`
`==> es: Provisioners will not be run since container doesn't support SSH.`
`==> spark: Provisioners will not be run since container doesn't support SSH.`
`==> scrapyd3: Provisioners will not be run since container doesn't support SSH.`
`==> scrapyd1: Provisioners will not be run since container doesn't support SSH.`
`==> redis: Provisioners will not be run since container doesn't support SSH.`

**Comment by lookfwd** [comment]
@LagartoSeb - tried to find you online. Please e-mail me to see what's not working on your system.

**Comment by sebastian-palma** [comment]
Hi @lookfwd, glad to have your answer, I have the commented behaviour trying to access the box after running `vagrant up --no-parallel`, I can't access through localhost:port, 0.0.0.0:port, nor http://web:port, the whole book is based on the Vagrant content to do the exercises and properly the content, so I don't how to continue with the book.

I'm not very happy using BeautifulSoup, that's why I wanted to read the book (:

**Comment by lookfwd** [comment]
Hello @LagartoSeb, I understand. Yes, Scrapy will give you a more complete framework than BeautifulSoup. You can see a comparison of the two frameworks [here](http://www.scrapinginsider.com/2016/01/scrapy-urllib2-requests-beautifulsoup-lxml.html).

What I see from the output and commands you've provided is that everything went fine with the installation and there's probably some small operational problem e.g. using incorrect host/port. From "outside the VM" you would be using the following ports.

![screen-shot-2016-07-04-at-09 08 22](https://cloud.githubusercontent.com/assets/789359/16554500/2a6aef44-41c7-11e6-9b64-74c044376a7c.png)

With Vagrant I give you 9 virtual servers pre-setup and although it might seem confusing, installing all this software properly would be close to impossible. As soon as you login to the system, all the examples will be working fine and you will have a system that you can operate in a similar way to a real production system.

Let's find out how to login though. Just send me an e-mail so we can chat, otherwise it will take too much time, figuring out if you use Windows, Mac etc. potentially going through putty settings... we will save time this way.

Cheers.

**Comment by sebastian-palma** [comment]
@lookfwd you're right, I very appreciate your attention, let's talk on Gitter

**Comment by lookfwd** [comment]
As far as I can tell, from our chat, this case is similar to [this](https://github.com/scalingexcellence/scrapybook/issues/5#issuecomment-231693501) i.e. linux and native run with docker. In your case, upgrading docker to a more recent version worked like charm.

**Comment by withkarlkarl** [comment]
seems that I have the same problem:

```
root@ubuntu:/home/junjiyang/scrapybook# vagrant up --no-parallel
Bringing machine 'web' up with 'docker' provider...
Bringing machine 'spark' up with 'docker' provider...
Bringing machine 'es' up with 'docker' provider...
Bringing machine 'redis' up with 'docker' provider...
Bringing machine 'mysql' up with 'docker' provider...
Bringing machine 'scrapyd1' up with 'docker' provider...
Bringing machine 'scrapyd2' up with 'docker' provider...
Bringing machine 'scrapyd3' up with 'docker' provider...
Bringing machine 'dev' up with 'docker' provider...
==> web: Provisioners will not be run since container doesn't support SSH.
==> spark: Provisioners will not be run since container doesn't support SSH.
==> es: Provisioners will not be run since container doesn't support SSH.
==> redis: Provisioners will not be run since container doesn't support SSH.
==> mysql: Provisioners will not be run since container doesn't support SSH.
==> scrapyd1: Provisioners will not be run since container doesn't support SSH.
==> scrapyd2: Provisioners will not be run since container doesn't support SSH.
==> scrapyd3: Provisioners will not be run since container doesn't support SSH.
==> dev: Provisioners will not be run since container doesn't support SSH.
```

I searched the web but not come to a solution.
I tried `vagrant ssh-config` somehow, and it send back to me like this:

```
Host web
  HostName 172.17.0.2
  User root
  Port 22
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /home/junjiyang/scrapybook/insecure_key
  IdentitiesOnly yes
  LogLevel FATAL

Host spark
  HostName 172.17.0.3
  User root
  Port 22
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /home/junjiyang/scrapybook/insecure_key
  IdentitiesOnly yes
  LogLevel FATAL

Host es
  HostName 172.17.0.4
  User root
  Port 22
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /home/junjiyang/scrapybook/insecure_key
  IdentitiesOnly yes
  LogLevel FATAL
.......................................
```

the **hostname (172.17.0.*)** of each **host(web, spark, etc.)** are diffirent from the book's table, which @lookfwd has already posted on this web-page earlier.

seems like I'm very close to a victory, But at this moment, I don't know what to do

P.S. I'm useing Ubuntu 14.03 under your suggestion. Only my Ubuntu is grow up on VMware12

**Comment by lookfwd** [comment]
Hello @withkarlkarl , you are running under Windows or Linux? Could you try this to see if it solves the problem? https://github.com/scalingexcellence/scrapybook/issues/5#issuecomment-236838937 . If you're on linux, the command is: `export SCRAPYBOOK_FORCE_HOST_VM=TRUE`

**Comment by withkarlkarl** [comment]
so fast! Thank You fist!
@lookfwd I'm running win10, but I use VMware to start a Ubuntu 14.03

**Comment by withkarlkarl** [comment]
THANK YOU VERY MUCH for your help!! @lookfwd 
but after I followed your advice it still not working:
![visualbox](http://obfoga5ye.bkt.clouddn.com/16-8-7/69894091.jpg)

and I tried download visualbox and install
after which I retried `vagrant up --no-parallel`, but a new problem come out:
![VBoxManage](http://obfoga5ye.bkt.clouddn.com/16-8-7/89165747.jpg)

**Comment by lookfwd** [comment]
Hello @withkarlkarl - could you e-mail me in lookfwd@gmail.com ?

**Comment by lafber** [comment]
Get the same issue here on MacOS with 

> Provisioners will not be run since container doesn't support SSH.

After running a `vagrant ssh-config`  and relaunching  `vagrant up --no-parallel` it works. Weird and not sure it cames from that but it is working now.
