### ISSUE TITLE
No usable default provider could be found for your system.

### ISSUE THREAD

**Issue by ghost** [scalingexcellence/scrapybook#12]
Hi. I followed the instructions from the book, and from https://docs.docker.com/engine/installation/linux/ubuntulinux/ to install vagrant and docker. First I attempted this on an Ubuntu 14.04 LTS install. After spending a day on trying to figure out how to get it to work I installed a fresh OS; this time Ubuntu 16.04 LTS. I have been trying for 3 days, and I am still having problems with getting this to work. The error is always identical in all of my attempted initializations:

~/scrapybook$ sudo vagrant up --no-parallel
Bringing machine 'web' up with 'docker' provider...
Bringing machine 'spark' up with 'docker' provider...
Bringing machine 'es' up with 'docker' provider...
Bringing machine 'redis' up with 'docker' provider...
Bringing machine 'mysql' up with 'docker' provider...
Bringing machine 'scrapyd1' up with 'docker' provider...
Bringing machine 'scrapyd2' up with 'docker' provider...
Bringing machine 'scrapyd3' up with 'docker' provider...
Bringing machine 'dev' up with 'docker' provider...
web: Docker host is required. One will be created if necessary...
No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
`vagrant up --provider=PROVIDER`, which should give you a more specific
error message for that particular provider."

Can you please help me?

**Comment by lookfwd** [comment]
Hello, what have you tried those 4 days? Did you try to install VirtualBox (from [here](https://www.virtualbox.org/wiki/Linux_Downloads)) as the message above says? 

> The easiest solution to this message is to install VirtualBox, which
> is available for free on all major platforms.

If this doesn't work, send me an e-mail and I will connect with TeamViewer.

**Comment by ghost** [comment]
Thank you for the prompt response.

The things I have tried in the past 4 days weren't very well thought out. Mostly just trying to reinstall everything several times. At one point I tried to make a docker image after ubuntu 14.04. (because docker said that it didn't have an image to make a container out of or something like that.) I tried running the docker Daemon from the terminal. I spent a good amount of time trying to interpret the vagrantfile, but I don't know Ruby; only Python. I learned some vagrant commands, and watched several tutorials on Docker and Vagrant; and tried to use those to help solve the problem. But that actually was more frustrating because the few resources that I could find on vagrant + docker all promised that everything would just work, right out of the box. I also think I actually had virtualbox installed at some point, but uninstalled it? I definitely had something that was supposed to go with vagrant, but was not docker. I might be confusing an installed virtualbox with vagrant for Portia (which was in a tutorial appearing in the Packtpub Web Scraping with Python book. Which I had just completed before starting on your book.) Basically, I just banged on the keyboard for 4 days hoping that by hitting it hard enough that I might get vagrant to work. Reinstalling the OS was also a desperate attempted solution, but I needed to update my Ubuntu from 14.04 anyways. 

The one thing I actually did not try was installing Virtualbox. The reason was because I did not have success with Portia when trying to install Virtualbox for the other tutorial, and I also thought that Virtualbox would possibly replace or somehow override Docker. I assumed that Docker, and Virtualbox were alternatives to the same function.

Well, Installing virtualbox seems to have solved the problem. vagrant up is now performing the downloading step. Thank you :)

**Comment by lookfwd** [comment]
Awesome! :)

> Basically, I just banged on the keyboard for 4 days hoping that by hitting it hard enough that I might get vagrant to work.

:) I know the feeling... I've spent long time going like "I WILL MAKE THIS WORK" (actually I do it right now with some other technology :) ) Vagrant/docker take time to master. If they don't "just work", I think, it's best to ask for help. I will update github's files to reflect this. But I seriously believe your way is the path to learning. Unfortunately a little bit painful now and then... but fun at the same time.

Anyway - I'm glad it worked! :) Cheers!
