### ISSUE TITLE
the host VM is still reporting that SSH is unavailable

### ISSUE THREAD

**Issue by ghost** [scalingexcellence/scrapybook#13]
Sorry for opening a new issue. I ran into some addition errors in the install, but I solved those. I am getting a new error now, and I am at a totally lost with this. I did a Google search, but there literally is not any useful information about this on the internet.

In solving a seemingly unrelated issue; I did have to make some changes to the vagrantfile.dockerhost file, but I don't expect that they should have caused any errors. Especially not causing the error that I am getting now. I am including this in case it is actually relevant. The reason for the changes are that my CPU does not support virtualization technology. Virtualization technology is expected to be on by default, for virtualbox. It had to be explicitly turned off for the VM. Also my machine only has 4GB of ram. So here are those changes:

```
# Set the mem/cpu requirements
config.vm.provider :virtualbox do |vb|
    vb.memory = 1024
    vb.cpus = 1
            ...
    vb.customize ["modifyvm", :id, "--hwvirtex", "off"]
```

The terminal session showing the error:
"
~/$ sudo vagrant destroy <id>
~/$ sudo vagrant up --no-parallel
....
docker-provider: SSH address: 127.0.0.1:2222
docker-provider: SSH username: vagrant
docker-provider: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
~/$
~/$ sudo vagrant up --no-parallel
...
web:  
docker-provider: Checking if box 'lookfwd/scrapybook' is up to date...
The Docker provider was able to bring up the host VM successfully
but the host VM is still reporting that SSH is unavailable. This
sometimes happens with certain providers due to bugs in the
underlying hypervisor, and can be fixed with a `vagrant reload`.
The ID for the host VM is shown below for convenience.

If this does not fix it, please verify that the host VM provider
is functional and properly configured.

Host VM ID: 581b3b42-9013-4e84-ae9f-6a8a48b67905
"

Oh, and I did attempt ~/$ vagrant reload <id> , but it just results in the same timeout error. I am not sure how to verify that the host VM provider is functional and properly configured. Doesn't the vagrantfile handle that?

**Comment by lookfwd** [comment]
Yeah - for the case of limited computers there's a 32-bit VM that supports all but the last chapter: https://github.com/scalingexcellence/scrapybook/issues/5#issuecomment-219987071

**Comment by ghost** [comment]
Unfortunately the solution doesn't seem to apply. I have been trying to use the Vagrantfile.32 since you've posted. The symptoms have changed, but it is still behaving in a way that seems to reflect an SSH or some other network problem.

I first tried the Vagrantfile.32 straight out of the box, and without modification (withholding the change made to the file extension, of course.) This generated the same VT-x error as previously mentioned.

I then added "vb.customize ["modifyvm", :id, "--hwvirtex", "off"]" to the Vagrantfile.32 file, again still getting the VT-x error.

The full solution had to be applied to Vagrantfile.32 to suppress the VT-x error. 

After modifying Vagrantfile.32 and running "vagrant up --no-parallel", I got this message again:
"docker-provider: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period."

Running "vagrant up --no-parallel" a second time, with no manual change in state, I get this message:
"Bringing machine 'scrapy-vm-32' up with 'virtualbox' provider...
==> scrapy-vm-32: Checking if box 'lookfwd/scrapybook32' is up to date...
~/$
"
and running the command a third time, just to be sure:

"Bringing machine 'scrapy-vm-32' up with 'virtualbox' provider...
==> scrapy-vm-32: Checking if box 'lookfwd/scrapybook32' is up to date...
==> scrapy-vm-32: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> scrapy-vm-32: flag to force provisioning. Provisioners marked to run always will still run.
"

So all is good right? 

Unfortunately when I type any of the following URL's into the browser address bar:
"web:9312/properties/property_000000.html"
"localhost:web:9312/properties/property_000000.html"
"web:9312"
"localhost:web:9312"

The browser just hangs forever, waiting for the response.

If the browser is trying to access web:9312, and I run "vagrant destroy <id>" from the terminal, then the browser resolves; saying the typical "page cannot be found" error.

I also have tried various combinations of the 3 Vagrantfiles ('Vagrantfile.32', 'Vagrantfile', 'Vagrantfile.host'). For example, I've tried changing the name of 'Vagrantfile.32' to 'Vagrantfile.host', and as I am sure that you expect, it say 'docker-provider' can't be found (or something like that.) 

When vagrant is active and stable, by running ~/$ virtualbox ; the virtualbox GUI pops up, but no VM is listed. Although vagrant global-status does list a VM.

I don't know if it makes a difference, but I am pretty sure that my machine is 64 bit. I run Ubuntu 64 bit, I have ran FL Studio 64 bit. The CPU definitely does not support virtualization technology though. I first checked BIOS, and the option was not present. I ran the command from the terminal with grep to search for svm, and (I don't remember the other name,) to which neither requirement was present. I then found an online technical resource specifically for my CPU. Alas, VT is not supported. That issue, of non-supporting architecture, was solved by adding the three lines to the Vagrantfile. When I went through this process of modifying the Vagrantfile, I did so incrementally in both cases (for Vagrantfile, and for Vagrantfile.32,) from the bottom up. The system simply would not run until I had added every line.

Am I over looking something in all of this?

**Comment by ghost** [comment]
Also, perhaps unrelated, but as soon as I sent the last post: all of my machines went off the network,  but my brothers did not. My tablet recovered first, after I shut my laptop down (where I was running vagrant.) My laptop took several minutes to recover connectivity after reboot. Vagrant was active at the time.

update: various machines keep going on and off the network. lol

Reseting the router fixed the connectivity issues.

**Comment by lookfwd** [comment]
A few summarizing points:

a) The easy solution for me is to say that your machine isn't supported and I'm fine. I don't need to fix it for a machine that doesn't have Virtualization extensions... everything beyond this is a bonus
b) I don't need to comment on Vagrant hacks and I highly discourage anyone from hacking Vagrantfiles. If it doesn't work, send a post here or on the e-mail as you did and I will find a solution. It takes months and lots of pain to get on an intermediate level with Vagrant and all those VM stuff and if you spend just a few hours all you will be able to contribute is part of your feelings of pain... which are irrelevant to Scrapy and the book. If Vagrant doesn't work, don't fix it.

Overall, I will try to contact you on the e-mail and fix your system. If there's something I believe might be of interest to other people I will come back and report. Otherwise, we're good for now.

P.S. "localhost:web:9312/properties/property_000000.html", "localhost:web:9312" aren't valid URLs. "localhost:9312/properties/property_000000.html", "localhost:9312" might work.

**Comment by lookfwd** [comment]
There was also an issue with unsupported, by default, network card. See 5a6600abec

**Comment by ghost** [comment]
I will definitely check that out. thanks a million, I would have never figured out how to get it to run properly.

**Comment by lookfwd** [comment]
Cheers! Yes, VM's are very tricky. Unless you get them "exactly right" they will bite you sooner or later. Enjoy!
