### ISSUE TITLE
Issue with Virtualbox 5.1.6 a,d Vagrant 1.8.5

### ISSUE THREAD

**Issue by mic0331** [scalingexcellence/scrapybook#14]
On my ubuntu 16.04 64bit I noticed an error when using the Virtualbox version 5.1.6 and vagrant version 1.8.5

```
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "c2bd3fe0-48f7-463d-b31c-80720472de13", "--type", "headless"]

Stderr: VBoxManage: error: The virtual machine 'docker-provider' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
```

I simply downgrade to Virtual box 5.0.0 and now it works perfectly.

I log this issue and close it so anyone encountering this issue can have a workaround.

**Comment by lookfwd** [comment]
With some googling "NS_ERROR_FAILURE (0x80004005)` I see all sorts of such errors around with various root causes e.g. [antivirus](https://forums.virtualbox.org/viewtopic.php?f=6&t=68869). Most people resolve by re-installing various components.
