### ISSUE TITLE
“The host VM is still reporting that SSH is unavailable”

### ISSUE THREAD

**Issue by eqyzou** [scalingexcellence/scrapybook#17]
Hello, 

When I was running "vagrant up --no-parallel", I encountered the following error message. I have no idea on how to fix it. Do you have any advice? Thanks a lot!

==> web: Docker host is required. One will be created if necessary...
    web: Vagrant will now create or start a local VM to act as the Docker
    web: host. You'll see the output of the `vagrant up` for this VM below.
    web:  
    docker-provider: Checking if box 'lookfwd/scrapybook' is up to date...
The Docker provider was able to bring up the host VM successfully
but the host VM is still reporting that SSH is unavailable. This
sometimes happens with certain providers due to bugs in the
underlying hypervisor, and can be fixed with a `vagrant reload`.
The ID for the host VM is shown below for convenience.

If this does not fix it, please verify that the host VM provider
is functional and properly configured.

Host VM ID: d7219853-07ee-499e-8bf6-1fac9b3c3888

**Comment by lookfwd** [comment]
Hello, is it Windows or Linux? Have you watched this one? https://www.youtube.com/watch?v=r84-dsIRFI8 Does it diverge at some specific point?

**Comment by tzatter** [comment]
Same issue with Ubuntu 16.04

$ vagrant up --no-parallel Bringing machine 'web' up with 'docker' provider...
Bringing machine 'spark' up with 'docker' provider...
Bringing machine 'es' up with 'docker' provider...
Bringing machine 'redis' up with 'docker' provider...
Bringing machine 'mysql' up with 'docker' provider...
Bringing machine 'scrapyd1' up with 'docker' provider...
Bringing machine 'scrapyd2' up with 'docker' provider...
Bringing machine 'scrapyd3' up with 'docker' provider...
Bringing machine 'dev' up with 'docker' provider...
==> web: Docker host is required. One will be created if necessary...
No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
`vagrant up --provider=PROVIDER`, which should give you a more specific
error message for that particular provider.

**Comment by tzatter** [comment]
SOLVED: force_host_vm = FALSE on line 4 of Vagrantfile
Sorry for I haven't read before the issue

**Comment by lookfwd** [comment]
Thanks for figuring it out. I have to find a way - like a permanent issue or something to develop an FAQ. I can see installation-related requests going up :)
