### ISSUE TITLE
Vagrant not finding Docker provider

### ISSUE THREAD

**Issue by ghost** [scalingexcellence/scrapybook#18]
I have a clean AWS m4.large Ubuntu 14.04.5 and have followed the Appendix A to the letter.

I am getting this error. 

ubuntu@ xxxxxxxxxxxx:~$ git clone https://github.com/scalingexcellence/scrapybook.git
Cloning into 'scrapybook'...
remote: Counting objects: 1181, done.
remote: Total 1181 (delta 0), reused 0 (delta 0), pack-reused 1181
Receiving objects: 100% (1181/1181), 614.42 KiB | 0 bytes/s, done.
Resolving deltas: 100% (579/579), done.
Checking connectivity... done.
ubuntu@ xxxxxxxxxxxx:~$ cd scrapybook/
ubuntu@ xxxxxxxxxxxx ~/scrapybook$ ls
README.md  Vagrantfile  Vagrantfile.32  Vagrantfile.dockerhost  Vagrantfile.dockerhost.src  ch03  ch04  ch05  ch06  ch07  ch08  ch09  ch10  ch11  insecure_key  lint
ubuntu@xxxxxxxxxxxx:~/scrapybook$ vagrant up --no-parallel
Bringing machine 'web' up with 'docker' provider...
Bringing machine 'spark' up with 'docker' provider...
Bringing machine 'es' up with 'docker' provider...
Bringing machine 'redis' up with 'docker' provider...
Bringing machine 'mysql' up with 'docker' provider...
Bringing machine 'scrapyd1' up with 'docker' provider...
Bringing machine 'scrapyd2' up with 'docker' provider...
Bringing machine 'scrapyd3' up with 'docker' provider...
Bringing machine 'dev' up with 'docker' provider...
==> web: Docker host is required. One will be created if necessary...
No usable default provider could be found for your system.

I ran with the --provider=docker but same

also ran with --debug on and noticed this:
INFO handle_box: Skipping HandleBox because no box is set
 INFO warden: Calling IN action: #<Proc:0x00000000d43140@/opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::ConfigValidate:0x0000000184b6f0>
 INFO warden: Calling IN action: #<VagrantPlugins::DockerProvider::Action::HostMachine:0x0000000184b6c8>
 INFO interface: output: Docker host is required. One will be created if necessary...
 INFO interface: output: ==> web: Docker host is required. One will be created if necessary...

The $USER env $PATH does not have /opt set, unless you do. - not sure this is relative

Both Docker and Vagrant work from the command line.

**Comment by lookfwd** [comment]
Hello @19dc60, could you give a quick go to setting `force_host_vm = FALSE` on line 4 of `Vagrantfile`

**Comment by ghost** [comment]
Hello Dimitrios

My sincere thank you for your speedy response. That was the issue. 
Docker ps returns 9 instances.

I look forward to following your examples and appreciate the effort you have put into covering the basic technologies as well as the purpose of your book.

Regards

David

**Comment by lookfwd** [comment]
Excellent! Thanks a lot David - I hope you enjoy the book! :)
