### ISSUE TITLE
Can't access the /book files in the dev machine

### ISSUE THREAD

**Issue by pedrini210** [scalingexcellence/scrapybook#19]
Hi,

I'm currently on Windows 10 and I've setup the environment.

I run the `vagrant up --no-parallel` command and get this:

`C:\scrapybook>vagrant up --no-parallel`
`Bringing machine 'web' up with 'docker' provider...`
`Bringing machine 'spark' up with 'docker' provider...`
`Bringing machine 'es' up with 'docker' provider...`
`Bringing machine 'redis' up with 'docker' provider...`
`Bringing machine 'mysql' up with 'docker' provider...`
`Bringing machine 'scrapyd1' up with 'docker' provider...`
`Bringing machine 'scrapyd2' up with 'docker' provider...`
`Bringing machine 'scrapyd3' up with 'docker' provider...`
`Bringing machine 'dev' up with 'docker' provider...`
`==> web: Docker host is required. One will be created if necessary...`
`    web: Docker host VM is already ready.`
`==> web: Starting container...`
`==> web: Provisioners will not be run since container doesn't support SSH.`
`==> spark: Docker host is required. One will be created if necessary...`
`    spark: Docker host VM is already ready.`
`==> spark: Vagrant has noticed that the synced folder definitions have changed.`
`==> spark: With Docker, these synced folder changes won't take effect until you`
`==> spark: destroy the container and recreate it.`
`==> spark: Starting container...`
`==> spark: Provisioners will not be run since container doesn't support SSH.`
`==> es: Docker host is required. One will be created if necessary...`
`    es: Docker host VM is already ready.`
`==> es: Starting container...`
`==> es: Provisioners will not be run since container doesn't support SSH.`
`==> redis: Docker host is required. One will be created if necessary...`
`    redis: Docker host VM is already ready.`
`==> redis: Starting container...`
`==> redis: Provisioners will not be run since container doesn't support SSH.`
`==> mysql: Docker host is required. One will b`e created if `necessary...`
`    mysql: Docker host VM is already ready.`
`==> mysql: Starting container...`
`==> mysql: Provisioners will not be run since container doesn't support SSH.`
`==> scrapyd1: Docker host is required. One will be created if necessary...`
`    scrapyd1: Docker host VM is already ready.`
`==> scrapyd1: Starting container...`
`==> scrapyd1: Provisioners will not be run since container doesn't support SSH.`
`==> scrapyd2: Docker host is required. One will be created if necessary...`
`    scrapyd2: Docker host VM is already ready.`
`==> scrapyd2: Starting container...`
`==> scrapyd2: Provisioners will not be run since container doesn't support SSH.`
`==> scrapyd3: Docker host is required. One will be created if necessary...`
`    scrapyd3: Docker host VM is already ready.`
`==> scrapyd3: Starting container...`
`==> scrapyd3: Provisioners will not be run since container doesn't support SSH.`
`==> dev: Docker host is required. One will be created if necessary...`
`    dev: Docker host VM is already ready.`
`==> dev: Vagrant has noticed that the synced folder definitions have changed.`
`==> dev: With Docker, these synced folder changes won't take effect until you`
==> dev: destroy the container and recreate it.
==> dev: Starting container...
==> dev: Provisioners will not be run since container doesn't support SSH.`

Then I run the `vagrant ssh` command and follow the path to `/books` and it's empty...

`root@dev:~# ls`
`book`
`root@dev:~# cd book/`
`root@dev:~/book# ls`
` `

Here's a pic of the scrapybook directory

![image](https://cloud.githubusercontent.com/assets/17329313/20969475/81e973ea-bc5f-11e6-84ff-79fafe64ee31.png)

How can I solve this?

**Comment by lookfwd** [comment]
Hello, thanks a lot for the excellent report of this issue. It seems like the case "How do I fully reset the VM?" (238 on the book / page 259 on the pdf)

**Comment by pedrini210** [comment]
It worked! Thank you very much

**Comment by lookfwd** [comment]
Glad, awesome, thanks!
