### ISSUE TITLE
Learning Scrapy - How to get shared folders working between host (Mac OSX) and guest OS (Linux)?

### ISSUE THREAD

**Issue by lookfwd** [scalingexcellence/scrapybook#2]
Hey all, sorry for the newbie question. I am working through Dmitrios Kouzis-Loukas' book Learning Scrapy.  

In that book, he outlines how to setup a dev environment using Vagrant and Docker. I am having trouble getting the Shared Folders working so I can edit files in the dev environment using the text editor on my host machine. 

I have found a few write ups, but have not had success. I think that I need to install Guest Additions on the guest OS. How do I do this on the Linux guest OS? 

http://helpdeskgeek.com/virtualization/virtualbox-share-folder-host-guest/

Thank you, 

Matt

**Comment by lookfwd** [comment]
Hello Matt,

Appendix A has lots of details that worked on the variety of systems I tried it, but certainly there will be a couple that aren't covered by settings etc. If we accumulate all the relevant knowledge in this issue page it will be easier for everyone to track.

Installing Guest Additions is ok but there might be easier ways to go.

**Comment by lookfwd** [comment]
Please reopen or add a new one if anyone faces similar issue.

**Comment by lookfwd** [comment]
A few weeks and no follow-up. Please reopen or add a new one if anyone faces similar issue.

**Comment by ghost** [comment]
Hi I'm having this issue also. Did you end up finding a solution?

**Comment by lookfwd** [comment]
No, he (s)he never followed up - I guess (s)he found the solution by restarting the VM. @grs-adj what OS do you have? If it's Windows, at which point of the process highlighted in the video here: http://scrapybook.com/ did it stop working?

**Comment by ghost** [comment]
I'm using OSX and very new to using vagrant, docker and virtualbox. I can get the VM up and running but after that I have a couple of issues. When I ssh into dev the 'book' folder is empty. I believe it is supposed to have a copy of the book files (I do have these files on my local machine). The other is like the original comment I am unable to get the shared folders working. I feel like I'm missing something simple but I don't know what it is.

**Comment by lookfwd** [comment]
@grs-adj - makes sense. Please send me an e-mail on lookfwd@gmail.com in order to do a quick teamviewer session and figure out how to fix this.

**Comment by grs-adj** [comment]
@lookfwd will do
