### ISSUE TITLE
Installation on MAC

### ISSUE THREAD

**Issue by ghost** [scalingexcellence/scrapybook#20]
Hi. I have successfully installed on a remote AWS linux server but am experiencing an issue installing on my MAC.

I am getting the following error when committing the "vagrant up --no-parallel" command. 

_**The box 'lookfwd/scrapybook' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/lookfwd/scrapybook"]
Error: **_

I have noticed that if I copy the URL into a browser it returns a different URL - not sure if this helps. 

"https://atlas.hashicorp.com/lookfwd/boxes/scrapybook"

I have tried to the use the --provider virtualbox too.........I have grep'd my Vagrant files for this URL and thought I would ask you.

**Comment by lookfwd** [comment]
Hey - if you could e-mail me, we could do a TeamViewer session and see what the problem is. It sounds familiar but I can't tell what the exact problem is.

**Comment by 19dc60** [comment]
Hi Dimitrios

Do you wish to set up the team viewer meeting? 

I'm available now if you are. My apologies if this is a stupid question.

David

**Comment by 19dc60** [comment]
HI Dimitrios
I am trying to email to you directly. I do not see the option for that. 

David

**Comment by 19dc60** [comment]
HI Dimitrios 

my email is dcarradice@gmail.com

**Comment by 19dc60** [comment]
Hi again Dimitrios.

I appear to be unable to contact you at this moment.
If you are available tomorrow, please let me know a suitable time

Alternatively you can contact me directly via uk skype number 02081447460
or email dcarradice@gmail.com

Thank you

PS I am in Cyprus and GMT+2

**Comment by lookfwd** [comment]
This was an extremely hard to debug case. The main root cause was that it was using an older vagrant version 

    $ vagrant --version
    Vagrant 1.8.7

that was very buggy. As soon as I upgraded to 1.9.1 the VM installation worked fine.

    $ vagrant --version
    Vagrant 1.9.1

Now, in the process of figuring out what's going on, I tried the "native docker" flow. Apparently due to some relatively unusual security settings on that computer I was hitting a case similar to [this](https://github.com/mitchellh/vagrant-aws/issues/179) i.e. `vagrant ssh` was freezing. The whole docker installation was going fine but `vagrant ssh` didn't work. Upgrading to 1.9.1. didn't fix this either. In this case using virtualbox resolved the problem.

**Comment by liutao1992** [comment]
Hi, I also have meet similar problem. 
Here is my worker enviroment :
Operating System: Ubuntu 16.04
Vagrant version 1.9.2
virtual box has been installed.

I am getting the following error when committing the "vagrant up --no-parallel" command.

`Bringing machine 'web' up with 'docker' provider...
Bringing machine 'spark' up with 'docker' provider...
Bringing machine 'es' up with 'docker' provider...
Bringing machine 'redis' up with 'docker' provider...
Bringing machine 'mysql' up with 'docker' provider...
Bringing machine 'scrapyd1' up with 'docker' provider...
Bringing machine 'scrapyd2' up with 'docker' provider...
Bringing machine 'scrapyd3' up with 'docker' provider...
Bringing machine 'dev' up with 'docker' provider...
==> web: Docker host is required. One will be created if necessary...
    web: Vagrant will now create or start a local VM to act as the Docker
    web: host. You'll see the output of the `vagrant up` for this VM below.
    web:  
    docker-provider: Box 'lookfwd/scrapybook' could not be found. Attempting to find and install...
    docker-provider: Box Provider: virtualbox
    docker-provider: Box Version: >= 0
The box 'lookfwd/scrapybook' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/lookfwd/scrapybook"]
Error: The requested URL returned error: 404 Not Found
`
