### ISSUE TITLE
Issue on chater 3

### ISSUE THREAD

**Issue by OscarDgrouch** [scalingexcellence/scrapybook#23]
This is related to chapter 3, the book instructs me to run on Addess Item xpath =>  //*[@itemtype="http://schema.org/Place"][1]/text().
However I'm getting this:
In [27]: response.xpath('//*[@itemtype="http://schema.org/Place"][1]/text()').extract()
Out[27]: 
[u'\n  ',
 u'\n  ',
 u'\n  ',
 u'\n  ',
 u'\n  ',
 u'\n  ',
 u'\n  ',
 u'\n  ',
 u'\n  ',
 u'\n  ',
 u'\n  ',
 u'\n  ',
 u'\n  ',
 u'\n  ',
 u'\n  ',
 u'\n  ',
 u'\n  ',
 u'\n  ',
 u'\n  ',
 u'\n  ',
 u'\n  ',
 u'\n  ',
 u'\n  ',
 u'\n  ',
 u'\n  ',
 u'\n  ',
 u'\n  ',
 u'\n  ',
 u'\n  ',
 u'\n  ']

When I run it with out the text () I get this:
[u'<span itemscope itemtype="http://schema.org/Place">\n  <span>West Hampstead, London</span></span>',
 u'<span itemscope itemtype="http://schema.org/Place">\n  <span>Angel, London</span></span>',
 u'<span itemscope itemtype="http://schema.org/Place">\n  <span>Tower Bridge, London</span></span>',
 u'<span itemscope itemtype="http://schema.org/Place">\n  <span>Canary Wharf, London</span></span>',
 u'<span itemscope itemtype="http://schema.org/Place">\n  <span>Whitechapel, London</span></span>',
 u'<span itemscope itemtype="http://schema.org/Place">\n  <span>Chelsea, London</span></span>',
 u'<span itemscope itemtype="http://schema.org/Place">\n  <span>Hackney, London</span></span>',
 u'<span itemscope itemtype="http://schema.org/Place">\n  <span>Stratford, London</span></span>',
 u'<span itemscope itemtype="http://schema.org/Place">\n  <span>Canary Wharf, London</span></span>',
 u'<span itemscope itemtype="http://schema.org/Place">\n  <span>Chiswick, London</span></span>',
 u'<span itemscope itemtype="http://schema.org/Place">\n  <span>Highbury, London</span></span>',
 u'<span itemscope itemtype="http://schema.org/Place">\n  <span>Notting Hill, London</span></span>',
 u'<span itemscope itemtype="http://schema.org/Place">\n  <span>Brixton, London</span></span>',
 u'<span itemscope itemtype="http://schema.org/Place">\n  <span>Greenwich, London</span></span>',
 u'<span itemscope itemtype="http://schema.org/Place">\n  <span>Canary Wharf, London</span></span>',
 u'<span itemscope itemtype="http://schema.org/Place">\n  <span>Battersea, London</span></span>',
 u'<span itemscope itemtype="http://schema.org/Place">\n  <span>South Kensington, London</span></span>',
 u'<span itemscope itemtype="http://schema.org/Place">\n  <span>Camden, London</span></span>',
 u'<span itemscope itemtype="http://schema.org/Place">\n  <span>Wimbledon, London</span></span>',
 u'<span itemscope itemtype="http://schema.org/Place">\n  <span>West Hampstead, London</span></span>',
 u'<span itemscope itemtype="http://schema.org/Place">\n  <span>West Hampstead, London</span></span>',
 u'<span itemscope itemtype="http://schema.org/Place">\n  <span>Elephant And Castle, London</span></span>',
 u'<span itemscope itemtype="http://schema.org/Place">\n  <span>Angel, London</span></span>',
 u'<span itemscope itemtype="http://schema.org/Place">\n  <span>Heathrow, London</span></span>',
 u'<span itemscope itemtype="http://schema.org/Place">\n  <span>Bayswater, London</span></span>',
 u'<span itemscope itemtype="http://schema.org/Place">\n  <span>Seven Sisters, London</span></span>',
 u'<span itemscope itemtype="http://schema.org/Place">\n  <span>Angel, London</span></span>',
 u'<span itemscope itemtype="http://schema.org/Place">\n  <span>Angel, London</span></span>',
 u'<span itemscope itemtype="http://schema.org/Place">\n  <span>Battersea, London</span></span>',
 u'<span itemscope itemtype="http://schema.org/Place">\n  <span>Bethnal Green, London</span></span>']
I tried paying with it and I came up with this:
In [32]: response.xpath('//*[@itemtype="http://schema.org/Place"][1]/span/text()').extract()
Out[32]: 
[u'West Hampstead, London',
 u'Angel, London',
 u'Tower Bridge, London',
 u'Canary Wharf, London',
 u'Whitechapel, London',
 u'Chelsea, London',
 u'Hackney, London',
 u'Stratford, London',
 u'Canary Wharf, London',
 u'Chiswick, London',
 u'Highbury, London',
 u'Notting Hill, London',
 u'Brixton, London',
 u'Greenwich, London',
 u'Canary Wharf, London',
 u'Battersea, London',
 u'South Kensington, London',
 u'Camden, London',
 u'Wimbledon, London',
 u'West Hampstead, London',
 u'West Hampstead, London',
 u'Elephant And Castle, London',
 u'Angel, London',
 u'Heathrow, London',
 u'Bayswater, London',
 u'Seven Sisters, London',
 u'Angel, London',
 u'Angel, London',
 u'Battersea, London',
 u'Bethnal Green, London']

**My questions which xpath expresion is right????? And why I'm getting an array instead of single values???

**Comment by lookfwd** [comment]
Hello, I see what you mean. I can confirm that:

    scrapy shell http://web:9312/properties/index_00000.html
    >>> response.xpath('//*[@itemtype="http://schema.org/Place"][1]/text()').extract()
    [u'\n  ', ... u'\n  ', u'\n  ']
    >>> response.xpath('//*[@itemtype="http://schema.org/Place"][1]/span/text()').extract()
    [u'West Hampstead, London', ... , u'Bethnal Green, London']

The only issue is that in the context of Chapter you want to be crawling individual pages e.g.

    scrapy shell http://web:9312/properties/property_000000.html
    >>> response.xpath('//*[@itemtype="http://schema.org/Place"][1]/text()').extract()
    [u'West Hampstead, London']

In Chapter 5, page 99 you can find how to crawl the index pages directly with relative XPaths (see also [here](https://doc.scrapy.org/en/latest/topics/selectors.html#working-with-relative-xpaths)).

P.S. Sorry for the typo - they are mentioned as "Relevant XPath" in that page.
