### ISSUE TITLE
Could you tell me the root name and password of the docker-provider ?

### ISSUE THREAD

**Issue by polar9527** [scalingexcellence/scrapybook#24]
Could you tell me the root name and password of the docker-provider ?

**Comment by lookfwd** [comment]
Hello @polar9527. Could you try to see if those two commands give you ssh to docker-provider? No password should be necessary.

```
alias provider_id="vagrant global-status --prune | grep 'docker-
provider' | awk '{print \$1}'"
vagrant ssh $(provider_id)
```

**Comment by polar9527** [comment]
I has already solved my problem by the vedio on http://scrapybook.com . Thanks anyway!
