### ISSUE TITLE
vagrant ssh command got error

### ISSUE THREAD

**Issue by rezafarhadur** [scalingexcellence/scrapybook#25]
I am using ubuntu 16.04.
I have follow all steps and that works properly.
But when run ``vagrant ssh`` it shows

`==> dev: The container is not currently running.`

How i can run this container or run **vagrant ssh**

**Comment by lookfwd** [comment]
Sounds like `vagrant up --no-parallel` didn't start properly. Interesting. I'm wondering what `vagrant status` gives. Does it seem to run? In any case, let's do a teamviewer session - it usually takes little time to fix. which timezone are you at?

**Comment by rezafarhadur** [comment]
## ``vagrant status`` results:

`````
Current machine states:

web                       preparing (docker)
spark                     preparing (docker)
es                        preparing (docker)
redis                     preparing (docker)
mysql                     preparing (docker)
scrapyd1                  preparing (docker)
scrapyd2                  preparing (docker)
scrapyd3                  preparing (docker)
dev                       preparing (docker)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.
`````

#### vagrant version: Vagrant 1.9.3

#### docker version: Docker version 17.03.0-ce, build 60ccb22

**Comment by FarhadurFahim** [comment]
Is there any wrong? If you need more info let me know.
btw, my time zone is UTC +6.

**Comment by lookfwd** [comment]
UTC + 6... tricky! Now it's 4 am there... Could you send me an e-mail ( lookfwd@gmail.com) ... and then we will setup a TeamViewer session.

**Comment by FarhadurFahim** [comment]
Sure i can, i will send email now.

**Comment by lookfwd** [comment]
Seems to be a Vagrant 1.9.3 issue. I fixed it and posted an issue in Vagrant's github: https://github.com/mitchellh/vagrant/issues/8423
