### ISSUE TITLE
Chapter 3 example pg 36-40

### ISSUE THREAD

**Issue by johnscrapetest87** [scalingexcellence/scrapybook#27]
Hello Dimitrios, 

was running some of the example problems in the scrapy shell...just wanted to know, did the web url 
web:9312/properties/property_000000.html change its content or format relative to what is in the textbook on pg 36-37?  When I ran some of the response.xpath ..... I get different answers than what the book has....for example>>> response.xpath('//*[@itemprop="price"] [1]/text()').exctract returns now............

<bound method SelectorList.extract of [<Selector xpath='//*[@itemprop="price"] [1]/text()' data=u'\n\xa3715.0pw'>]>

but the book has  the same response returning just [u'\xa3334.39pw']    

all of this is on page 37

i dont mind if the web page changed but wondered if there is an updated set of answers for the textbook........

thankks John

appreciate the help with the vagrant/windows10 bug....

**Comment by lookfwd** [comment]
> appreciate the help with the vagrant/windows10 bug....

Welcome! :)

> i dont mind if the web page changed but wondered if there is an updated set of answers for the textbook........

Seems like typo(s) to me (noticed 2) ;)

**Comment by lookfwd** [comment]
P.S. I mean that as far as I can see the book (page 37) is correct. They are typos in copy-paste or typing (at least on what you wrote above) :)
