### ISSUE TITLE
vagrant up --no-parallel error

### ISSUE THREAD

**Issue by ctenix** [scalingexcellence/scrapybook#33]
Hi,
I have installed the newest vagrant (Vagrant 1.9.5) and docker-ce on ubuntu 16.04.1.
But when I run the "vagrant up --no-parallel ", it output the error like this:
vagrant up --provider=docker
Bringing machine 'web' up with 'docker' provider...
Bringing machine 'spark' up with 'docker' provider...
Bringing machine 'es' up with 'docker' provider...
Bringing machine 'redis' up with 'docker' provider...
Bringing machine 'mysql' up with 'docker' provider...
Bringing machine 'scrapyd1' up with 'docker' provider...
Bringing machine 'scrapyd2' up with 'docker' provider...
Bringing machine 'scrapyd3' up with 'docker' provider...
Bringing machine 'dev' up with 'docker' provider...
==> web: Docker host is required. One will be created if necessary...
==> es: Docker host is required. One will be created if necessary...
==> scrapyd3: Docker host is required. One will be created if necessary...
==> redis: Docker host is required. One will be created if necessary...
==> scrapyd1: Docker host is required. One will be created if necessary...
==> spark: Docker host is required. One will be created if necessary...
==> dev: Docker host is required. One will be created if necessary...
==> scrapyd1: An error occurred. The error will be shown after all tasks complete.
==> web: An error occurred. The error will be shown after all tasks complete.
==> es: An error occurred. The error will be shown after all tasks complete.
==> scrapyd2: Docker host is required. One will be created if necessary...
==> spark: An error occurred. The error will be shown after all tasks complete.
==> mysql: Docker host is required. One will be created if necessary...
==> scrapyd3: An error occurred. The error will be shown after all tasks complete.
==> redis: An error occurred. The error will be shown after all tasks complete.
==> dev: An error occurred. The error will be shown after all tasks complete.
==> scrapyd2: An error occurred. The error will be shown after all tasks complete.
==> mysql: An error occurred. The error will be shown after all tasks complete.
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An error occurred while executing the action on the 'web'
machine. Please handle this error then try again:

No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
`vagrant up --provider=PROVIDER`, which should give you a more specific
error message for that particular provider.

Also it can run "docker run hello-world" well in my machine.

Hope to get help.

**Comment by lookfwd** [comment]
Hello, I see `vagrant up --provider=docker` somewhere in the logs. Did you explicitly or implicitly set the provider to docker? Because if that's the case, one should also turn `force_host_vm = FALSE` at the beginning of `Vagrantfile` because of various incompatibilities that arose after the book was published.

**Comment by fengben** [comment]
GMT+8 thank you

**Comment by webdeveloper3514** [comment]
webserver: An error occurred. The error will be shown after all tasks complete.
 database: Removing domain...
database: An error occurred. The error will be shown after all tasks complete.
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An error occurred while executing the action on the 'webserver'
machine. Please handle this error then try again:

Error while removing network ansible-learn1. Call to virNetworkDestroy failed: Requested operation is not valid: network 'ansible-learn1' is not active.

An error occurred while executing the action on the 'database'
machine. Please handle this error then try again:

Error while removing network ansible-learn1. Call to virNetworkDestroy failed: Requested operation is not valid: network 'ansible-learn1' is not active.

**Comment by webdeveloper3514** [comment]
webserver: An error occurred. The error will be shown after all tasks complete.
 database: Removing domain...
database: An error occurred. The error will be shown after all tasks complete.
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An error occurred while executing the action on the 'webserver'
machine. Please handle this error then try again:

Error while removing network ansible-learn1. Call to virNetworkDestroy failed: Requested operation is not valid: network 'ansible-learn1' is not active.

An error occurred while executing the action on the 'database'
machine. Please handle this error then try again:

Error while removing network ansible-learn1. Call to virNetworkDestroy failed: Requested operation is not valid: network 'ansible-learn1' is not active.
