### ISSUE TITLE
Stderr:docker Error

### ISSUE THREAD

**Issue by preethamninja** [scalingexcellence/scrapybook#34]
I am relatively new to vagrant and docker.
i get the following error when i perform the following command.
vagrant up --no-parallel

A Docker command executed by Vagrant didn't complete successfully!
The command run along with the output from the command is shown
below.

```
Command: "docker" "run" "--name" "spark" "-d" "-p" "21:21" "-p" "30000:30000" "-p" "30001:30001" "-p" "30002:30002" "-p" "30003:30003" "-p" "30004:30004" "-p" "30005:30005" "-p" "30006:30006" "-p" "30007:30007" "-p" "30008:30008" "-p" "30009:30009" "-v" "var\lib\docker\docker_1495457854_50822:/root/book" "-h" "spark" "scrapybook/spark"

Stderr: docker: Error response from daemon: create var\lib\docker\docker_1495457854_50822: volume name invalid: "var\\lib\\docker\\docker_1495457854_50822" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed.
See 'docker run --help'.

```

**Comment by lookfwd** [comment]
I haven't seen this before. What operating system, vagrant version, is virtualbox installed etc?

**Comment by preethamninja** [comment]
Operating System: Windows sever 2016
Vagrant version 1.9.5
Yes virtual box has been installed

**Comment by lookfwd** [comment]
Ok, sounds good. In which timezone are you? Might we be able to do a teemviewer session sometime later today/tomorrow to fix this?

**Comment by preethamninja** [comment]
i am free now, will be available for another 6 hours, you can let me know when you are free , so will come online at that time.

**Comment by ghost** [comment]
Hi,

I am having the same issue on Windows, Were you able to resolve this ? Many thanks.

**Comment by lookfwd** [comment]
I will be available around 9:00 PM EST. Could you guys e-mail me at lookfwd@gmail.com to connect and fix this? I apologize, but every time there's a new vagrant release, always something breaks.

**Comment by k7e7n7t** [comment]
Same issue here...
Windows 10
Vagrant 1.9.5
VirtualBox 5.1.22 r115126
Docker 17.04.0-ce, build 4845c56

Thank you.

**Comment by k7e7n7t** [comment]
Based on your comment about "every time there's a new vagrant release, always something breaks" I downgraded to 1.8.5 and now it works fine...

**Comment by lookfwd** [comment]
Yep, 1.9.2 is the last stable one. That said, I will hopefully connect to someone's PC or reproduce the error myself and see if I can pinpoint the issue. I'll see if there's a workaround I can put on the Vagrantfile or open yet another vagrant issue.

**Comment by preethamninja** [comment]
Hi, downgrading to a older version worked, thanks a lot for the help.

**Comment by lookfwd** [comment]
I tried to reproduce this with 1.9.5 tonight. I got even more weird errors but somewhat later. I'll look at them. The error you're you're getting, highly likely is the one from https://github.com/mitchellh/vagrant/issues/8608. I would revert the change they mention there (https://github.com/mitchellh/vagrant/commit/5d83c03bfc48407451999f21b0320a1ebb22a8cd) to see if it fixes it and contribute that to the discussion in https://github.com/mitchellh/vagrant/issues/8608.

**Comment by lookfwd** [comment]
For resolution, see issue #32. Will likely be fixed in future vagrant version.

**Comment by lookfwd** [comment]
There was another bug in Vagrant causing this. This is the fix: https://github.com/mitchellh/vagrant/pull/8921

**Comment by robertodijo** [comment]
:-) I can bang my head. I love your book "Learning Scrapy". But I also hit the same error, and tried to fixed it myself. Though I know docker and vagrant very well. However, I was not aware of the bug. After hours of trail and error, I saw this post. I will downgrade vagrant, and see if thinks work.

**Comment by lookfwd** [comment]
Try also [this](https://github.com/hashicorp/vagrant/pull/8921/files) fix, it shouldn't be that hard to apply - just 3 tiny edits. Yes - very annoying bug and it remained alive for waaay too long :)

**Comment by yhLe0** [comment]
hello, have you solved this problem?
