### ISSUE TITLE
Windows Host error: volume name invalid (Solved)

### ISSUE THREAD

**Issue by mattheuspirovani** [scalingexcellence/scrapybook#37]
I was facing the following issue:

```
Stderr: docker: Error response from daemon: create var\lib\docker\docker_1499653205_62199: volume name invalid: "var\\lib\\docker\\docker_1499653205_62199" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_
.-]" are allowed.
```
Changed in the Vagrantfile, the lines 43 & 168, respectively:

from:
` spark.vm.synced_folder ".", "/root/book"`
to:
`spark.vm.synced_folder ".", "/vagrant", disabled: true`

from:
`dev.vm.synced_folder ".", "/root/book"`
to:
`dev.vm.synced_folder ".", "/vagrant", disabled: true`

So, works smoothly...

**BTW, i'm a vagrant/docker newbie and cant guarantee that's the right solution. Hope that a expert can explain if i made a mistake.**

**Comment by lookfwd** [comment]
Hello, thanks for sharing! Just to clarify, this is Vagrant 1.9.7, on Windows and it refers on getting the examples from Chapter 11 running, right? It looks the same with issue #34.

**Comment by mattheuspirovani** [comment]
@lookfwd Yes, Vagrant 1.9.7 on Windows. I was setting up the environment...

Thanks for the reply.

**Comment by mattheuspirovani** [comment]
Recreated my env using Vagrant 1.9.2 and now everything is fine.
