### ISSUE TITLE
problem starting Vagrant

### ISSUE THREAD

**Issue by polarisresearch2** [scalingexcellence/scrapybook#40]
Hi, I have struggled with Vagrant, desperately need some help.

Here is my environment:
1. host PC: windows 10 pro
2. docker for windows is installed
3. installed a Bash for Ubuntu for windows (for the Linux environment)
4. installed Docker in the Ubuntu (docker works fine in Ubuntu, I've tested it)
5. installed Vagrant, Git, etc.

When I start Vagrant, I first ran into error "No usable default provider could be found for your system", I corrected it by changing force_host_vm from TRUE to FALSE; then I am having another error:

Command: ["docker", "run", "--name", "spark", "-d", "-p", "21:21", "-p", "30000:30000", "-p", "30001:30001", "-p", "30002:30002", "-p", "30003:30003", "-p", "30004:30004", "-p", "30005:30005", "-p", "30006:30006", "-p", "30007:30007", "-p", "30008:30008", "-p", "30009:30009", "-v", "home\\myusername\\scrapybook:/root/book", "-v", "home\\myusername\\scrapybook:/vagrant", "-h", "spark", "scrapybook/spark", {:notify=>[:stdout, :stderr]}]

I do not know where "home\\myusername\\scrapybook" comes from, I have searched all over Vagrant and docker-compose file, and replaced all possible places with absolute path "/home/myusername/scrapybook"

thanks!
javelinlz

**Comment by lookfwd** [comment]
Hello @javelinlz,

This looks like it started the same as #34 and others. Recent Vagrants are broken. I would use the default version out-of the box with git (i.e. undo the ). There are two solutions:

* Downgrade to Vagrant 1.9.2
* Apply this patch I've sent them: https://github.com/hashicorp/vagrant/pull/8921/files

If you want - I can have a look at it through TeamViewer

P.S. there was no need for installing ubuntu + docker in ubuntu. Win-only should be fine.

**Comment by shixiangbupt** [comment]
D:\scrapybook>vagrant up --no-parallel
D:/scrapybook/Vagrantfile:4: warning: constant ::TRUE is deprecated
Bringing machine 'web' up with 'docker' provider...
Bringing machine 'spark' up with 'docker' provider...
Bringing machine 'es' up with 'docker' provider...
Bringing machine 'redis' up with 'docker' provider...
Bringing machine 'mysql' up with 'docker' provider...
Bringing machine 'scrapyd1' up with 'docker' provider...
Bringing machine 'scrapyd2' up with 'docker' provider...
Bringing machine 'scrapyd3' up with 'docker' provider...
Bringing machine 'dev' up with 'docker' provider...
==> web: Docker host is required. One will be created if necessary...
The version of powershell currently installed on this host is less than
the required minimum version. Please upgrade the installed version of
powershell to the minimum required version and run the command again.

  Installed version: 2

  Minimum required version: 3

**Comment by WSOL12** [comment]
This is again about upgrading powershell: https://docs.microsoft.com/en-us/powershell/scripting/setup/installing-windows-powershell?view=powershell-6
