### ISSUE TITLE
docker-provider: Booting VM error

### ISSUE THREAD

**Issue by SLeonidV** [scalingexcellence/scrapybook#41]
After last october Windows 10 Version 1703 x64 updating my vagrant up --no-parallel has next error:
"...
docker-provider: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "cd8f2d95-2d3c-44d5-a57f-16c594a357f5", "--type", "headless"]

Stderr: VBoxManage.exe: error: The virtual machine 'docker-provider' has terminated unexpectedly during startup with exit code -1073741819 (0xc0000005)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine"

Could you please help me to fix that issue?

**Comment by lookfwd** [comment]
hello, what timezobe are you at? I can have a quick look

**Comment by SLeonidV** [comment]
@lookfwd thanks for reply.I have decided to use scrapy without vagrant.
