### ISSUE TITLE
link to XPath functions documentation broken

### ISSUE THREAD

**Issue by gViro** [scalingexcellence/scrapybook#45]
In the Chapter 2 section: "Selecting HTML elements with XPath", the link to documentation of XPath functions (http://www.w3schools.com/xsl/xpath_functions.asp) returns a 404 response. 

MDN has a list of them here: https://developer.mozilla.org/en-US/docs/Web/XPath/Functions

**Comment by lookfwd** [comment]
Yeah - links (you don't control) on printed books are useless... :/ They moved it here: https://www.w3schools.com/xml/xsl_functions.asp
