### ISSUE TITLE
unknown host

### ISSUE THREAD

**Issue by csankaraiah** [scalingexcellence/scrapybook#48]
I followed all the steps to setup vagrant on my mac machine. i was able to connect to web server but not any more. When i try to ping the server it says unknown host. This i am doing from inside the dev machine.

```
root@dev:/etc# whoami
root
root@dev:/etc# hostname
dev
root@dev:/etc# ping http://web:9312/properties/property_000000.html
ping: unknown host http://web:9312/properties/property_000000.html
root@dev:/etc#
```

Please let me know how i can resolve this

**Comment by MoAbdelgani** [comment]
I have the same issue, it looks like the dev machine is somehow can't see the host directory. When you do ls command you see both scrappy project folder and book folder in blue color and not in green color.

![image](https://user-images.githubusercontent.com/37767140/38448483-633e5388-39d2-11e8-9308-8ad51f9a3658.png)

**Comment by WSOL12** [comment]
`ping web` should work. `ping http://web:9312/properties/property_000000.html` shouldn't, but `curl http://web:9312/properties/property_000000.html` should.
