### ISSUE TITLE
'vagrant up --no-parallel ' do not work!

### ISSUE THREAD

**Issue by shixiangbupt** [scalingexcellence/scrapybook#49]
D:\scrapybook>vagrant up --no-parallel
D:/scrapybook/Vagrantfile:4: warning: constant ::TRUE is deprecated
Bringing machine 'web' up with 'docker' provider...
Bringing machine 'spark' up with 'docker' provider...
Bringing machine 'es' up with 'docker' provider...
Bringing machine 'redis' up with 'docker' provider...
Bringing machine 'mysql' up with 'docker' provider...
Bringing machine 'scrapyd1' up with 'docker' provider...
Bringing machine 'scrapyd2' up with 'docker' provider...
Bringing machine 'scrapyd3' up with 'docker' provider...
Bringing machine 'dev' up with 'docker' provider...
==> web: Docker host is required. One will be created if necessary...
The version of powershell currently installed on this host is less than
the required minimum version. Please upgrade the installed version of
powershell to the minimum required version and run the command again.

  Installed version: 2

  Minimum required version: 3

**Comment by lxl2603** [comment]
Please upgrade the installed version of powershell. Reference: 
  https://blog.csdn.net/i_am_wangbo/article/details/50033473

**Comment by WSOL12** [comment]
Thanks @lxl2603
