### ISSUE TITLE
 vagrant up --no-parallel   ?

### ISSUE THREAD

**Issue by shixiangbupt** [scalingexcellence/scrapybook#50]
PS D:\> cd .\scrapybook
PS D:\scrapybook> vagrant up --no-parallel
D:/scrapybook/Vagrantfile:4: warning: constant ::TRUE is deprecated
Bringing machine 'web' up with 'docker' provider...
Bringing machine 'spark' up with 'docker' provider...
Bringing machine 'es' up with 'docker' provider...
Bringing machine 'redis' up with 'docker' provider...
Bringing machine 'mysql' up with 'docker' provider...
Bringing machine 'scrapyd1' up with 'docker' provider...
Bringing machine 'scrapyd2' up with 'docker' provider...
Bringing machine 'scrapyd3' up with 'docker' provider...
Bringing machine 'dev' up with 'docker' provider...
==> web: Docker host is required. One will be created if necessary...
The version of powershell currently installed on this host is less than
the required minimum version. Please upgrade the installed version of
powershell to the minimum required version and run the command again.

  Installed version: 2

  Minimum required version: 3
PS D:\scrapybook>

**Comment by leon0707** [comment]
Your powershell is outdated.

**Comment by WSOL12** [comment]
Thanks @leon0707
