### ISSUE TITLE
vagrant up error

### ISSUE THREAD

**Issue by hurun** [scalingexcellence/scrapybook#56]
I finish all appendix in the book, when i run vagrant up command , the error was happen.
i use some time in google to find result, all of not working.
could you help me to fixed it. i am new one to scarpy but has some skill in data analysis.
thank you so much, hope you can see this.

$ vagrant up
C:/Users/胡润/scrapybook/Vagrantfile:4: warning: constant ::TRUE is deprecated
Bringing machine 'web' up with 'docker' provider...
Bringing machine 'spark' up with 'docker' provider...
Bringing machine 'es' up with 'docker' provider...
Bringing machine 'redis' up with 'docker' provider...
Bringing machine 'mysql' up with 'docker' provider...
Bringing machine 'scrapyd1' up with 'docker' provider...
Bringing machine 'scrapyd2' up with 'docker' provider...
Bringing machine 'scrapyd3' up with 'docker' provider...
Bringing machine 'dev' up with 'docker' provider...
==> redis: Docker host is required. One will be created if necessary...
==> spark: Docker host is required. One will be created if necessary...
==> dev: Docker host is required. One will be created if necessary...
==> scrapyd3: Docker host is required. One will be created if necessary...
==> web: Docker host is required. One will be created if necessary...
==> scrapyd1: Docker host is required. One will be created if necessary...
==> mysql: Docker host is required. One will be created if necessary...
==> scrapyd2: Docker host is required. One will be created if necessary...
==> es: Docker host is required. One will be created if necessary...
    scrapyd3: Vagrant will now create or start a local VM to act as the Docker
    scrapyd3: host. You'll see the output of the `vagrant up` for this VM below.
    scrapyd3:
    docker-provider: Importing base box 'lookfwd/scrapybook'...
==> scrapyd3: An error occurred. The error will be shown after all tasks complete.
    scrapyd2: Vagrant will now create or start a local VM to act as the Docker
    scrapyd2: host. You'll see the output of the `vagrant up` for this VM below.
    scrapyd2:
    docker-provider: Importing base box 'lookfwd/scrapybook'...
==> scrapyd2: An error occurred. The error will be shown after all tasks complete.
    mysql: Vagrant will now create or start a local VM to act as the Docker
    mysql: host. You'll see the output of the `vagrant up` for this VM below.
    mysql:
    docker-provider: Importing base box 'lookfwd/scrapybook'...
==> mysql: An error occurred. The error will be shown after all tasks complete.
    es: Vagrant will now create or start a local VM to act as the Docker
    es: host. You'll see the output of the `vagrant up` for this VM below.
    es:
    docker-provider: Importing base box 'lookfwd/scrapybook'...
==> es: An error occurred. The error will be shown after all tasks complete.
    scrapyd1: Vagrant will now create or start a local VM to act as the Docker
    scrapyd1: host. You'll see the output of the `vagrant up` for this VM below.
    scrapyd1:
    docker-provider: Importing base box 'lookfwd/scrapybook'...
==> scrapyd1: An error occurred. The error will be shown after all tasks complete.
    web: Vagrant will now create or start a local VM to act as the Docker
    web: host. You'll see the output of the `vagrant up` for this VM below.
    web:
    docker-provider: Importing base box 'lookfwd/scrapybook'...
==> web: An error occurred. The error will be shown after all tasks complete.
    spark: Vagrant will now create or start a local VM to act as the Docker
    spark: host. You'll see the output of the `vagrant up` for this VM below.
    spark:
    docker-provider: Importing base box 'lookfwd/scrapybook'...
==> spark: An error occurred. The error will be shown after all tasks complete.
    redis: Vagrant will now create or start a local VM to act as the Docker
    redis: host. You'll see the output of the `vagrant up` for this VM below.
    redis:
    docker-provider: Importing base box 'lookfwd/scrapybook'...
==> redis: An error occurred. The error will be shown after all tasks complete.
    dev: Vagrant will now create or start a local VM to act as the Docker
    dev: host. You'll see the output of the `vagrant up` for this VM below.
    dev:
    docker-provider: Importing base box 'lookfwd/scrapybook'...
==> dev: An error occurred. The error will be shown after all tasks complete.
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An unexpected error occurred when executing the action on the
'web' machine. Please report this as a bug:

incompatible character encodings: GBK and UTF-8

D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/childprocess-0.6.3/lib/childprocess/windows/process_builder.rb:43:in `join'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/childprocess-0.6.3/lib/childprocess/windows/process_builder.rb:43:in `create_command_pointer'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/childprocess-0.6.3/lib/childprocess/windows/process_builder.rb:27:in `start'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/childprocess-0.6.3/lib/childprocess/windows/process.rb:70:in `launch_process'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/childprocess-0.6.3/lib/childprocess/abstract_process.rb:82:in `start'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/util/subprocess.rb:153:in `block in execute'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/util/safe_chdir.rb:26:in `block (2 levels) in safe_chdir'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/util/safe_chdir.rb:25:in `chdir'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/util/safe_chdir.rb:25:in `block in safe_chdir'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/util/safe_chdir.rb:24:in `synchronize'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/util/safe_chdir.rb:24:in `safe_chdir'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/util/subprocess.rb:152:in `execute'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/util/subprocess.rb:22:in `execute'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/providers/virtualbox/driver/base.rb:451:in `block in raw'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/util/busy.rb:19:in `busy'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/providers/virtualbox/driver/base.rb:450:in `raw'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/providers/virtualbox/driver/base.rb:388:in `block in execute'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/util/retryable.rb:17:in `retryable'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/providers/virtualbox/driver/base.rb:383:in `execute'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/providers/virtualbox/driver/version_5_0.rb:348:in `import'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/providers/virtualbox/action/import.rb:53:in `import'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/providers/virtualbox/action/import.rb:13:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/providers/virtualbox/action/prepare_clone_snapshot.rb:17:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/builtin/prepare_clone.rb:15:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/providers/virtualbox/action/customize.rb:40:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/builder.rb:116:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/runner.rb:66:in `block in run'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/util/busy.rb:19:in `busy'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/runner.rb:66:in `run'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/builtin/call.rb:53:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/builder.rb:116:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/runner.rb:66:in `block in run'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/util/busy.rb:19:in `busy'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/runner.rb:66:in `run'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/builtin/call.rb:53:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/builder.rb:116:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/runner.rb:66:in `block in run'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/util/busy.rb:19:in `busy'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/runner.rb:66:in `run'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/machine.rb:239:in `action_raw'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/machine.rb:208:in `block in action'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/environment.rb:614:in `lock'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/machine.rb:194:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/machine.rb:194:in `action'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/providers/docker/action/host_machine.rb:59:in `block in setup_host_machine'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/machine.rb:568:in `block in with_ui'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/machine.rb:564:in `synchronize'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/machine.rb:564:in `with_ui'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/providers/docker/action/host_machine.rb:58:in `setup_host_machine'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/providers/docker/action/host_machine.rb:28:in `block in call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/providers/docker/provider.rb:118:in `block (2 levels) in host_vm_lock'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/environment.rb:614:in `lock'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/providers/docker/provider.rb:117:in `block in host_vm_lock'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/providers/docker/provider.rb:116:in `synchronize'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/providers/docker/provider.rb:116:in `host_vm_lock'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/providers/docker/action/host_machine.rb:27:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/builtin/handle_box.rb:25:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/builder.rb:116:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/runner.rb:66:in `block in run'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/util/busy.rb:19:in `busy'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/runner.rb:66:in `run'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/builtin/call.rb:53:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/builder.rb:116:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/runner.rb:66:in `block in run'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/util/busy.rb:19:in `busy'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/runner.rb:66:in `run'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/machine.rb:239:in `action_raw'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/machine.rb:208:in `block in action'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/environment.rb:614:in `lock'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/machine.rb:194:in `call'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/machine.rb:194:in `action'
D:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

An unexpected error occurred when executing the action on the
'spark' machine. Please report this as a bug:

incompatible character encodings: GBK and UTF-8

**Comment by WSOL12** [comment]
> 胡润

This is highly likely because of the "胡润" on the username. It breaks vagrant :/ Maybe try to put `scrapybook` to another directory e.g. `C:\tmp\` instead of the `C:/Users/胡润/`
