### ISSUE TITLE
Different spider produces the data, stored in a different database or table

### ISSUE THREAD

**Issue by xiaowenjie21** [scalingexcellence/scrapybook#7]
If there are two spider, each of item['field'] are not the same, but requires the storage of different tables or databases, how to use different pipelines.py?

**Comment by lookfwd** [comment]
Hello, You can use `custom_settings` in your spider to override settings e.g. the destination table/database. An example of overriding settings from the spider can be found [here](http://stackoverflow.com/a/34230197/832887). Would that help?

**Comment by xiaowenjie21** [comment]
Thanks
